# Site settings
title: Raul Negron's Webpage
email: raul@raulnegron.me
description: > # this means to ignore newlines until "baseurl:"
  Computer Science student at the Univeristy of Puerto Rico at Rio Piedras.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raulnegron.me" # the base hostname & protocol for your site
github_username:  rnegron

# Build settings
markdown: kramdown
theme: minima
permalink: /blog/:year/:month/:day/:title
plugins:
    - jekyll-sitemap
